[project]
name = "zeppelin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anytree>=2.13.0",
    "canopen>=2.4.1",
    "cbor>=1.0.0",
    "clang-format>=15.0.0",
    "colorama>=0.4.6",
    "coverage>=7.14.3",
    "gcovr>=6.0",
    "gitlint>=0.19.1",
    "gitpython>=3.1.50",
    "graphviz>=0.21",
    "intelhex>=2.3.0",
    "junit2html>=31.1.4",
    "junitparser>=5.0.1",
    "lpc-checksum>=3.0.0",
    "lxml>=6.1.1",
    "mock>=4.0.1",
    "mypy>=2.1.0",
    "natsort>=8.4.0",
    "packaging>=26.2",
    "patool>=4.0.5",
    "pillow>=10.0",
    "ply>=3.10",
    "progress>=1.6.1",
    "psutil>=7.2.2",
    "pyelftools>=0.29",
    "pygithub>=2.9.1",
    "pykwalify>=1.8.0",
    "pylink-square>=1.7.0",
    "pylint>=3",
    "pyocd>=0.35.0",
    "pyserial>=3.5",
    "pytest>=9.1.1",
    "python-can>=4.3.0",
    "python-magic>=0.4.27 ; sys_platform != 'win32'",
    "python-magic-bin>=0.4.14 ; sys_platform == 'win32'",
    "pyyaml>=6.0",
    "requests>=2.34.2",
    "ruff==0.8.1",
    "semver>=3.0.4",
    "sphinx-lint>=1.0.2",
    "tabulate>=0.10.0",
    "tqdm>=4.68.3",
    "unidiff>=0.7.5",
    "west>=0.14.0",
    "windows-curses>=2.4.2 ; sys_platform == 'win32'",
    "yamllint>=1.38.0",
]
